parameters:
    set_from_email: jayraj.arora@gmail.com

services:
    password.encode:
      class: Jedi\UserBundle\Utils\EncodePassword
      arguments: [@security.encoder_factory]

    email.send:
          class: Jedi\UserBundle\Utils\SendEmail
          arguments: [@doctrine.orm.entity_manager,@templating,@mailer,"%set_from_email%"]

    validate:
        class: Jedi\UserBundle\Utils\Validation
        arguments: [@doctrine.orm.entity_manager]
